install.packages("htmlwidgets")
install.packages("DT")
install.packages("googleVis")
install.packages("dplyr")
install.packages("plyr")
install.packages("reshape2")
install.packages("RColorBrewer")

install.packages("FrissButtonGroup_0.1.4.tar.gz",repos = NULL,type="source")
install.packages("FrissIntroJS_0.4.tar.gz",repos = NULL,type="source")
install.packages("FrissNotie_0.1.0.tar.gz",repos = NULL,type="source")
install.packages("FrissMessageBox_1.2.tar.gz",repos = NULL,type="source")
install.packages("FrissC3Charts_1.2.0.tar.gz",repos = NULL,type="source")
install.packages("FrissSwitch_0.1.tar.gz",repos=NULL,type="source")